accounts/urls.py
from django.urls import path

from .views import UserProfileView, EditProfile, AddFollower, RemoveFollower

app_name="accounts"

urlpatterns = [
    path('<username>/', UserProfileView, name="profile"),
    path('profile/edit', EditProfile, name="edit-profile"),

    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
	path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),

]

books/urls.py
from django.urls import path

from .views import (
    BooksView,  
    UserBooksListView,
    BookUpdateView,
    BooktDetailView,
)

app_name="books"

urlpatterns = [

    path('books/', BooksView.as_view(), name="books"),
    path('library/', UserBooksListView.as_view(), name="book-list"),

    path('library/<slug>/update/', BookUpdateView.as_view(), name="book-update"),

    path('library/<slug>/', BooktDetailView.as_view(), name="book-detail"),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('users/', include('accounts.urls', namespace='users')),

    path('social/', include('social.urls', namespace='social')),

    path('marketplace/', include('marketplace.urls', namespace="marketplace")),

    path('books/', include('books.urls', namespace="books")),

    path('groups/', include('groups.urls', namespace="groups")),

    path('services/', include('services.urls', namespace="services")),

    path('', HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groups/urls.py
from django.urls import path

from .views import (
    GroupsView,
    GrouptDetailView,
    UserGroupsListView,
    GroupUpdateView,
    MyPostulationsListView,
    PostulationsListView,
    GroupDeleteView,
    PostulationDeleteView,
    AddMember,
    GrouptMembersView,
    DeclineMember,
    RemoveeMember,
    MyGroupsListView,
    LeaveGroup,
    GroupSearch,
)

app_name="groups"

urlpatterns = [


    path('groups/', GroupsView.as_view(), name="groups"),

    path('list-groups/', UserGroupsListView.as_view(), name="group-list"),

    path('groups/<slug>/update/', GroupUpdateView.as_view(), name="group-update"),

    path('groups/delete/<int:pk>', GroupDeleteView.as_view(), name="group-delete"),


    path('groups/<slug>/', GrouptDetailView.as_view(), name="group-detail"),

    path('my-postulations/', MyPostulationsListView.as_view(), name="my-postulations"),

    path('postulations/', PostulationsListView.as_view(), name="postulations"),

    path('postulations/delete/<int:pk>', PostulationDeleteView.as_view(), name="postulation-delete"),

    path('postulation/<int:postulation_pk>/group/<int:pk>/reply',AddMember.as_view(), name='add-member'),

    path('member/<int:member_pk>/group/<int:pk>/reply',RemoveeMember.as_view(), name='remove-member'),


    path('declinepostulation/<int:postulation_pk>/group/<int:pk>/reply',DeclineMember.as_view(), name='decline-member'),

    path('members/<slug>/', GrouptMembersView.as_view(), name="members"),

    path('my-groups/', MyGroupsListView.as_view(), name="my-groups"),

    path('leavegroup/delete/<int:pk>', LeaveGroup.as_view(), name="leave-group"),

    path('search/', GroupSearch.as_view(), name="group-search"),


]

services/urls.py
from django.urls import path

from .views import (
    ServicesView,
    chooseView,
    EmpresaDetailView,
    CreateCompanyView,
    CompanyUpdateView,
    ServiceUpdateView,
    ServiceDeleteView,
    ILikeCompany,
    NotLikeCompany,
    ServiceDetailView,
    ServiceSearch,


)

app_name="services"

urlpatterns = [

    path('services/', ServicesView.as_view(), name="services"),

    path('company/', chooseView.as_view(), name="company"),

    path('company/<slug>/', EmpresaDetailView.as_view(), name="company-detail"),

    path('createCompany/', CreateCompanyView.as_view(), name="create-Company"),

    path('company/<slug>/update/', CompanyUpdateView.as_view(), name="company-update"),

    path('service/<slug>/update/', ServiceUpdateView.as_view(), name="service-update"),

    path('service/delete/<slug>', ServiceDeleteView.as_view(), name="service-delete"),

    path('service/<int:pk>/likeCompany/', ILikeCompany.as_view(), name='i-like'),
    path('service/<int:pk>/notLikedCompany/', NotLikeCompany.as_view(), name='not_like'),

    path('service/<slug>/', ServiceDetailView.as_view(), name="service-detail"),

    path('search/', ServiceSearch.as_view(), name="service-search"),




    
]

templates/components/sidebars/left/items.html
{% load static %}
{% if user.is_authenticated %}
<ul class="p-4">
    <li>
        <a href="{% url 'users:profile' user.username %}"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
            <img src="{{user.profile.picture.url}}" alt="Profile picture" class="w-10 h-10 rounded-full">
            <span class="font-semibold">{{user.username}}</span>
        </a>
    </li>

    <li>
        <a href="{% url 'marketplace:products' %}"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-store text-gray-500'></i>
            <span class="font-semibold">Negocio</span>
        </a>
    </li>

    <li class="border-b border-gray-200 dark:border-dark-third mt-6"></li>
    <p class="flex items-center space-x-2 p-2 dark:hover:bg-dark-third dark:focus:bg-dark-second">
        Recomendaciones
    </p>
    <li>
        <a href="{% url 'books:books' %}"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-bookmark text-gray-500'></i>
            <span class="font-semibold">Libros</span>
        </a>
    </li>
    <li>
        <a href="#"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-directions text-gray-500'></i>
            <span class="font-semibold">Lugares</span>
        </a>
    </li>
    <li>
        <a href="{% url 'groups:groups' %}"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-group text-gray-500'></i>
            <span class="font-semibold">Grupos</span>
        </a>
    </li>
    <!-- <li>
        <a href=""
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-group text-gray-500'></i>
            <span class="font-semibold">Adopciones</span>
        </a>
    </li> -->

    <li class="border-b border-gray-200 dark:border-dark-third mt-6"></li>
    <p class="flex items-center space-x-2 p-2 dark:hover:bg-dark-third dark:focus:bg-dark-second">
        Comunidad
    </p>
    <li>
        <a href="#"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-group text-gray-500'></i>
            <span class="font-semibold">Preguntas</span>
        </a>
    </li>
    <li>
        <a href="{% url 'services:services' %}"
            class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third dark:focus:bg-dark-second">
            <i class='bx bx-brush text-gray-500'></i>
            <span class="font-semibold">Servicios</span>
        </a>
    </li>


    <!-- {% comment %} 
    <li>
        <a href="#" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
            <span class="w-10 h-10 rounded-full grid place-items-center bg-gray-300 dark:bg-dark-second">
                <i class='bx bx-chevron-down'></i>
            </span>
            <span class="font-semibold">como etsa</span>
        </a>
    </li> 
    {% endcomment %} -->

</ul>
{% else %}



{% endif %}

templates/components/sidebars/left/sidebar.html
{% load static %}

{% include 'components/sidebars/left/items.html' %}

{% include 'components/footer.html' %}