core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('users/', include('accounts.urls', namespace='users')),

    path('social/', include('social.urls', namespace='social')),

    path('marketplace/', include('marketplace.urls', namespace="marketplace")),

    path('books/', include('books.urls', namespace="books")),

    path('groups/', include('groups.urls', namespace="groups")),

    path('services/', include('services.urls', namespace="services")),

    path('', HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groups/urls.py
from django.urls import path

from .views import (
    GroupsView,
    GrouptDetailView,
    UserGroupsListView,
    GroupUpdateView,
    MyPostulationsListView,
    PostulationsListView,
    GroupDeleteView,
    PostulationDeleteView,
    AddMember,
    GrouptMembersView,
    DeclineMember,
    RemoveeMember,
    MyGroupsListView,
    LeaveGroup,
    GroupSearch,
)

app_name="groups"

urlpatterns = [


    path('groups/', GroupsView.as_view(), name="groups"),

    path('list-groups/', UserGroupsListView.as_view(), name="group-list"),

    path('groups/<slug>/update/', GroupUpdateView.as_view(), name="group-update"),

    path('groups/delete/<int:pk>', GroupDeleteView.as_view(), name="group-delete"),


    path('groups/<slug>/', GrouptDetailView.as_view(), name="group-detail"),

    path('my-postulations/', MyPostulationsListView.as_view(), name="my-postulations"),

    path('postulations/', PostulationsListView.as_view(), name="postulations"),

    path('postulations/delete/<int:pk>', PostulationDeleteView.as_view(), name="postulation-delete"),

    path('postulation/<int:postulation_pk>/group/<int:pk>/reply',AddMember.as_view(), name='add-member'),

    path('member/<int:member_pk>/group/<int:pk>/reply',RemoveeMember.as_view(), name='remove-member'),


    path('declinepostulation/<int:postulation_pk>/group/<int:pk>/reply',DeclineMember.as_view(), name='decline-member'),

    path('members/<slug>/', GrouptMembersView.as_view(), name="members"),

    path('my-groups/', MyGroupsListView.as_view(), name="my-groups"),

    path('leavegroup/delete/<int:pk>', LeaveGroup.as_view(), name="leave-group"),

    path('search/', GroupSearch.as_view(), name="group-search"),


]

services/urls.py
from django.urls import path

from .views import (
    ServicesView,
    chooseView,
    EmpresaDetailView,
    CreateCompanyView,
    CompanyUpdateView,
    ServiceUpdateView,
    ServiceDeleteView,
    ILikeCompany,
    NotLikeCompany,
    ServiceDetailView,
    ServiceSearch,


)

app_name="services"

urlpatterns = [

    path('services/', ServicesView.as_view(), name="services"),

    path('company/', chooseView.as_view(), name="company"),

    path('company/<slug>/', EmpresaDetailView.as_view(), name="company-detail"),

    path('createCompany/', CreateCompanyView.as_view(), name="create-Company"),

    path('company/<slug>/update/', CompanyUpdateView.as_view(), name="company-update"),

    path('service/<slug>/update/', ServiceUpdateView.as_view(), name="service-update"),

    path('service/delete/<slug>', ServiceDeleteView.as_view(), name="service-delete"),

    path('service/<int:pk>/likeCompany/', ILikeCompany.as_view(), name='i-like'),
    path('service/<int:pk>/notLikedCompany/', NotLikeCompany.as_view(), name='not_like'),

    path('service/<slug>/', ServiceDetailView.as_view(), name="service-detail"),

    path('search/', ServiceSearch.as_view(), name="service-search"),




    
]

services/views.py
from django.shortcuts import render
from django.views import View

from django.core.paginator import Paginator

from django.shortcuts import render, redirect, get_object_or_404

from services.models import Empresa, Work, Homework, Image

from services.forms import EmpresaModelForm, TrabajoModelForm, HomeworkModelForm

from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView
from django.urls.base import reverse_lazy
from django.urls import reverse

from django.contrib import messages
from django.db.models import Q

import string
import random
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify


def random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


# def unique_slug_generator(instance, new_slug=None):
#     if new_slug is not None:
#         slug = new_slug
#     else:
#         slug = slugify(instance.nombre)
#         Klass = instance.__class__
#         max_length = Klass._meta.get_field('slug').max_length
#         slug = slug[:max_length]
#         qs_exists = Klass.objects.filter(slug=slug).exists()

#         if qs_exists:
#             new_slug = "{slug}-{randstr}".format(
#                 slug=slug[:max_length-5], randstr=random_string_generator(size=4))

#             return unique_slug_generator(instance, new_slug=new_slug)
#         return slug


class ServicesView(View):
    def get(self, request, *args, **kwargs):
        services = Work.objects.filter(active=True)

        digital_services_data = None

        if services:
            paginator = Paginator(services, 9)
            page_number = request.GET.get('page')
            digital_services_data = paginator.get_page(page_number)

        context = {
            'services': digital_services_data,
        }
        return render(request, 'services/services.html', context)


class EmpresaDetailView(LoginRequiredMixin, View):
    def get(self, request, slug, *args, **kwargs):
        company = Empresa.objects.get(slug=slug)
        services = Work.objects.filter(company=company)
        form = TrabajoModelForm()

        likes = company.likes.all()

        number_of_likes = len(likes)

        if len(likes) == 0:
            liked = False

        for like in likes:
            if like == request.user:
                liked = True
                break
            else:
                liked = False

        services_data = None

        if services:
            paginator = Paginator(services, 6)
            page_number = request.GET.get('page')
            services_data = paginator.get_page(page_number)

        context = {
            'company': company,
            'liked':liked,
            'services': services_data,
            'number_of_likes': number_of_likes,
            'form': form
        }
        return render(request, 'services/my-company.html', context)

    def post(self, request, slug, *args, **kwargs):
        company = get_object_or_404(Empresa, slug=slug)
        services = Work.objects.filter(company=company)

        if request.method == 'POST':
            form = TrabajoModelForm(request.POST, request.FILES)
            print(form)
            if form.is_valid():
                company = get_object_or_404(Empresa, slug=slug)
                name = form.cleaned_data.get('name')
                presentation = form.cleaned_data.get('presentation')
                price = form.cleaned_data.get('price')
                thumbnail = form.cleaned_data.get('thumbnail')
                slug = random_string_generator()

                p, created = Work.objects.get_or_create(
                    company=company, name=name, presentation=presentation, price=price, thumbnail=thumbnail, slug=slug)
                p.save()
                messages.add_message(
                    self.request,
                    messages.SUCCESS,
                    'Haz creado un nuevo trabajo'
                )
                return redirect("services:company-detail", slug=company.slug)
                

        if services:
            paginator = Paginator(services, 6)
            page_number = request.GET.get('page')
            services_data = paginator.get_page(page_number)

            likes = company.likes.all()

            number_of_likes = len(likes)

            context = {
                'company': company,
                'services': services_data,
                'number_of_likes': number_of_likes,
                'form': form
            }
            messages.add_message(
                self.request,
                messages.SUCCESS,
                form.errors
            )
            return render(request, 'services/my-company.html', context)


class chooseView(View):
    def get(self, request, *args, **kwargs):
        try:
            company_detail = Empresa.objects.get(user=self.request.user)
        except Empresa.DoesNotExist:
            return redirect("services:create-Company")
        return redirect("services:company-detail", slug=company_detail.slug)


class CreateCompanyView(View):
    def get(self, request, *args, **kwargs):
        form = EmpresaModelForm()

        context = {
            'form': form
        }
        return render(request, 'services/createCompany.html', context)

    def post(self, request, *args, **kwargs):
        form = EmpresaModelForm()
        if request.method == "POST":
            form = EmpresaModelForm(request.POST, request.FILES)
            if form.is_valid():
                form.user = request.user
                banner = form.cleaned_data.get('banner')
                picture = form.cleaned_data.get('picture')
                nombre = form.cleaned_data.get('nombre')
                description = form.cleaned_data.get('description')
                lugar = form.cleaned_data.get('lugar')
                category = form.cleaned_data.get('category')
                schedule = form.cleaned_data.get('schedule')
                direction = form.cleaned_data.get('direction')
                number = form.cleaned_data.get('number')
                urlChat = form.cleaned_data.get('urlChat')
                slug = random_string_generator()

                p, created = Empresa.objects.get_or_create(user=form.user, banner=banner, picture=picture, nombre=nombre, description=description,
                                                           category=category, lugar=lugar, urlChat=urlChat, schedule=schedule, direction=direction, number=number, slug=slug)
                p.save()
                messages.add_message(
                    self.request,
                    messages.SUCCESS,
                    'Se ha creado con éxito su empresa, ya puedes compartir tu trabajo'
                )
                return redirect("services:company-detail", slug=slug)

        context = {
            'form': form
        }
        return render(request, 'services/createCompany.html', context)


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "services/edit-company.html"
    form_class = EmpresaModelForm

    def get_queryset(self):
        return Empresa.objects.filter(user=self.request.user)

    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Se ha actualizado su empresa'
        )
        return reverse("services:services")


class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "services/edit-service.html"
    form_class = TrabajoModelForm

    def get_queryset(self):
        return Work.objects.filter(company__user=self.request.user)

    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Se ha actualizado correctamente'
        )
        return reverse("services:services")


class ServiceDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model=Work
    template_name='services/delete-service.html'
    
    def get_success_url(self):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Haz eliminado el trabajo correctamente'
        )
        return reverse_lazy("services:services")
    
    def test_func(self):
        
        work = self.get_object()
        return self.request.user == work.company.user


class ILikeCompany(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        company = Empresa.objects.get(pk=pk)
        company.likes.add(request.user)
        return redirect("services:company-detail", slug=company.slug)


class NotLikeCompany(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        company = Empresa.objects.get(pk=pk)
        company.likes.remove(request.user)
        return redirect("services:company-detail", slug=company.slug)


class ServiceSearch(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('query')
        service_list = Work.objects.filter(Q(name__icontains=query, active=True))
        number_of_services = len(service_list)
        context={
            'number_of_services':number_of_services,
            'service_list':service_list
        }
        return render(request, 'services/search.html', context)

class ServiceDetailView(View):
    def get(self, request, slug,*args, **kwargs):
        service = get_object_or_404(Work, slug=slug)
        form = HomeworkModelForm()
        context={
            'service':service,
            'form':form
        }
        return render(request, 'services/detail.html', context)
    def post(self, request, slug,*args, **kwargs):
            form=HomeworkModelForm(request.POST)

            files = request.FILES.getlist('image')
            if form.is_valid():

templates/services/delete-service.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_tags %}
{% load tailwind_filters %}

{% block title %}Comentario{% endblock title %}
{% block extra_head %}{% endblock extra_head %}

<!-- NAVBAR -->
{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


<!-- MAIN -->
<!-- left sidebar -->
{% block left_sidebar %}
{% include 'components/sidebars/left/sidebar.html' %}
{% endblock left_sidebar %}

<!-- main content -->
{% block content %}
    <div>
      <div class="bg-white dark:bg-dark-second shadow px-4 py-5 sm:rounded-lg sm:p-6">
        <div class="md:grid md:grid-cols-3 md:gap-6">
          <div class="md:col-span-1">
            <h3 class="text-lg font-medium leading-6 dark:text-dark-txt text-gray-900">¿Seguro?</h3>
            <p class="mt-1 text-sm dark:text-dark-txt text-gray-500">
              Después de eliminarlo no lo puedes recuperar.
            </p>
          </div>
          <div class="mt-5 md:mt-0 md:col-span-2">
          
              <form  method="POST" class="space-y-8" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="pt-5">
                      <div class="flex justify-end">
                      <a href="{% url 'services:services' %}" type="button" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                          Cancelar
                      </a>
                      <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white dark:bg-dark-third  bg-red-500 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                          Eliminar
                      </button>
                      </div>
                  </div>
              </form>
            
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

<!-- right content -->
{% block right_sidebar %}
{% include 'components/sidebars/right/sidebar.html' %}
{% endblock right_sidebar %}

{% block javascript %}{% endblock javascript %}

templates/services/search.html
{% extends 'users/base.html'%}
{% load static %}

{% block title %}Servicios{% endblock title %}
{% block extra_head %}{% endblock extra_head %}

{% load humanize %}
{% load tailwind_tags %}
{% load tailwind_filters %}

{% block navbar %}
{% include 'components/navbarServices.html' %}
{% endblock navbar %}

{% block content %}


<div >
    <div class="bg-white max-w-full  shadow px-4 py-5 sm:rounded-lg sm:p-6 mt-10">
            <div class="dark:bg-dark-third max-w-full px-4 py-5 border-b rounded-lg mb-2 dark:border-dark-second border-gray-200 sm:px-6">

                <h3 class="text-xl leading-6 cursor-default dark:text-dark-txt prose rounded font-bold text-gray-900">
                    {{number_of_services}} Resultados 
                </h3>
                <p class="mt-1 text-sm cursor-default dark:text-dark-txt text-gray-500">
                    Estos son todos los resultados que encontramos.
                </p>
            </div>
            <ul class="grid grid-cols-2 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                {% for service in service_list %}
                <div class="flex-1 bg-white p-6 flex flex-col justify-between border rounded-lg mb-2 dark:border-dark-second border-gray-200 sm:px-6">
                    <div class="flex-1">
                        <p class="text-sm font-medium text-blue-600">
                            <a>
                                {{service.company.category}}
                            </a>
                        </p>
                        <span class="text-sm text-gray-500">{{service.created_on|naturaltime}}</span>
                        <a href="{% url 'services:service-detail' service.slug %}" class="block mt-2">
                            <p class="text-xl font-semibold text-gray-900">
                                {{service.name}}
                            </p>
                            {% if service.price %}
                            <p class="text-base font-semibold text-gray-400">
                                ${{service.price_display}}
                            </p>
                            {% endif %}
                        </a>
                    </div>
                    <div class="mt-6 flex items-center">
                        <div class="flex-shrink-0">
                            <a href="{% url 'services:company-detail' service.company.slug %}">
                                <span class="sr-only">{{service.company}}</span>
                                <img class="h-10 w-10 rounded-full" src="{{service.company.picture.url}}" alt="">
                            </a>
                        </div>
                        
                        <div class="ml-3">
                            <p class="text-sm font-medium text-gray-900">
                                <a href="{% url 'services:company-detail' service.company.slug %}" class="hover:underline">
                                    {{service.company}}
                                </a>
                            </p>
                            <div class="flex space-x-1 text-sm text-gray-500">
                                <span>
                                    {{service.company.lugar}}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </ul>
    </div>
</div>








{% endblock content %}


{% block javascript %}
{% endblock javascript %}

templates/services/services.html
{% extends 'baseMarketplace.html' %}
{% load static %}

{% block title %}Servicios{% endblock title %}
{% block extra_head %}{% endblock extra_head %}

{% load humanize %}
{% load tailwind_tags %}
{% load tailwind_filters %}

{% block navbar %}
{% include 'components/navbarServices.html' %}
{% endblock navbar %}


{% block content %}
{% if user.is_authenticated %}
<div x-data="{ open: false }" class="px-4 mt-4 shadow rounded-lg bg-white dark:bg-dark-second">
    <div class="p-2 flex">
        <a href="{% url 'services:company'%}"
            class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-blue-500">
            <i class='bx bxs-briefcase-alt-2'></i>
            <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Mi empresa</span>
        </a>
        <a href="#"
            class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-green-600">
            <i class='bx bx-run'></i>
            <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Mis trabajos</span>
        </a>
        <a href="#"
            class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-yellow-500">
            <i class='bx bx-paint-roll'></i>
            <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">trabajos</span>
        </a>
    </div>
</div>
{% else %}
<div class="px-4 mt-4 shadow rounded-lg bg-white dark:bg-dark-second">
    <div class="p-2 flex">
        <a href="{% url 'services:company'%}"
            class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-blue-500">
            <i class='bx bx-store-alt' ></i>
            <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Negocios</span>
        </a>
        <a href="{% url 'services:services'%}"
            class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-green-600">
            <i class='bx bx-briefcase'></i>
            <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Servicios</span>
        </a>
        <a href="{% url 'groups:groups'%}"
            class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-yellow-500">
            <i class='bx bxs-group'></i>
            <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Grupos</span>
        </a>
    </div>
</div>

{% endif %}

<div class="relative bg-gray-50 pt-16 pb-20 px-4 sm:px-6 lg:pt-24 lg:pb-28 lg:px-8">
    <div class="absolute inset-0">
        <div class="bg-white h-1/3 sm:h-2/3"></div>
    </div>
    <div class="relative max-w-7xl mx-auto">
        <div class="text-center">
            <h2 class="text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">
                Servicios
            </h2>
        </div>
        <div class="mt-12 max-w-lg mx-auto grid gap-5 lg:grid-cols-3 lg:max-w-none">
            {% for service in services %}
            <div class="flex flex-col rounded-lg shadow-lg overflow-hidden">
                <div class="flex-shrink-0">
                    {% if service.thumbnail %}
                    <a href="{% url 'services:service-detail' service.slug %}" class="block mt-2">
                        <img class="h-48 w-full object-cover" src="{{service.thumbnail.url}}" alt="">
                    </a>
                    {% endif %}
                </div>

                <div class="flex-1 bg-white p-6 flex flex-col justify-between">
                    <div class="flex-1">
                        <p class="text-sm font-medium text-blue-600">
                            {% if service.company.category %}
                            <a>
                                {{service.company.category}}
                            </a>
                            {% endif %}
                        </p>
                        
                        <a href="{% url 'services:service-detail' service.slug %}" class="block mt-2">
                            <p class="text-xl font-semibold text-gray-900">
                                {{service.name}}
                            </p>
                            {% if service.company.lugar %}
                            <p class="text-base font-semibold text-gray-400">
                                {{service.company.lugar}}
                            </p>
                            {% endif %}

                            <p class="float-right mt-3 text-base text-gray-500">
                                ${{service.price_display}}
                            </p>
                        </a>
                    </div>
                    <div class="mt-6 flex items-center">
                        <div class="flex-shrink-0">
                            <a href="{% url 'services:company-detail' service.company.slug %}">
                                <img class="h-10 w-10 rounded-full"
                                    src="{{service.company.picture.url}}"
                                    alt="">
                            </a>
                        </div>
                        <div class="ml-3">
                            <p class="text-sm font-medium text-gray-900">
                              <a href="{% url 'services:company-detail' service.company.slug %}" class="hover:underline">
                                {{service.company}}
                              </a>
                            </p>
                            <div class="flex space-x-1 text-sm text-gray-500">
                              <time datetime="2020-03-16">
                                {{service.created_on|naturaltime}}
                              </time>
                            </div>
                          </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


    {% if services.has_other_pages %}
    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
        <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
            <div>
                <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px" aria-label="Pagination">

                    {% if services.has_previous %}
                    <a href="?page={{ services.previous_page_number }}"
                        class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                        <span class="sr-only">Previous</span>
                        <!-- Heroicon name: solid/chevron-left -->
                        <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </a>
                    {% endif %}


                    {% for i in services.paginator.page_range %}
                    {% if services.number == i %}
                    <a href="?page={{ i }}" aria-current="page"
                        class="z-10 bg-gray-50 border-gray-500 text-blue-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium">
                        {{ i }}</a>
                    {% else %}
                    <a href="?page={{ i }}" aria-current="page"
                        class="z-10 bg-indigo-50 border-indigo-500 text-blue-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium">
                        {{ i }}</a>
                    {% endif %}
                    {% endfor %}


                    {% if services.has_next %}
                    <a href="?page={{ services.next_page_number }}"
                        class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                        <span class="sr-only">Next</span>
                        <!-- Heroicon name: solid/chevron-right -->
                        <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </a>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
    {% endif %}







</div>

{% endblock content %}


{% block javascript %}

{% endblock javascript %}