accounts/urls.py
from django.urls import path

from .views import UserProfileView, EditProfile, AddFollower, RemoveFollower

app_name="accounts"

urlpatterns = [
    path('<username>/', UserProfileView, name="profile"),
    path('profile/edit', EditProfile, name="edit-profile"),

    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
	path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('users/', include('accounts.urls', namespace='users')),

    path('social/', include('social.urls', namespace='social')),

    path('marketplace/', include('marketplace.urls', namespace="marketplace")),

    path('books/', include('books.urls', namespace="books")),

    path('groups/', include('groups.urls', namespace="groups")),

    path('services/', include('services.urls', namespace="services")),

    path('', HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groups/urls.py
from django.urls import path

from .views import (
    GroupsView,
    GrouptDetailView,
    UserGroupsListView,
    GroupUpdateView,
    MyPostulationsListView,
    PostulationsListView,
    GroupDeleteView,
    PostulationDeleteView,
    AddMember,
    GrouptMembersView,
    DeclineMember,
    RemoveeMember,
    MyGroupsListView,
    LeaveGroup,
    GroupSearch,
)

app_name="groups"

urlpatterns = [


    path('groups/', GroupsView.as_view(), name="groups"),

    path('list-groups/', UserGroupsListView.as_view(), name="group-list"),

    path('groups/<slug>/update/', GroupUpdateView.as_view(), name="group-update"),

    path('groups/delete/<int:pk>', GroupDeleteView.as_view(), name="group-delete"),


    path('groups/<slug>/', GrouptDetailView.as_view(), name="group-detail"),

    path('my-postulations/', MyPostulationsListView.as_view(), name="my-postulations"),

    path('postulations/', PostulationsListView.as_view(), name="postulations"),

    path('postulations/delete/<int:pk>', PostulationDeleteView.as_view(), name="postulation-delete"),

    path('postulation/<int:postulation_pk>/group/<int:pk>/reply',AddMember.as_view(), name='add-member'),

    path('member/<int:member_pk>/group/<int:pk>/reply',RemoveeMember.as_view(), name='remove-member'),


    path('declinepostulation/<int:postulation_pk>/group/<int:pk>/reply',DeclineMember.as_view(), name='decline-member'),

    path('members/<slug>/', GrouptMembersView.as_view(), name="members"),

    path('my-groups/', MyGroupsListView.as_view(), name="my-groups"),

    path('leavegroup/delete/<int:pk>', LeaveGroup.as_view(), name="leave-group"),

    path('search/', GroupSearch.as_view(), name="group-search"),


]

groups/models.py
from django.db import models
from django.conf import settings
import os
from django.utils import timezone

User = settings.AUTH_USER_MODEL

def group_directory_path(instance, filename):
    banner_pic_name = 'groups/groups/{0}/{1}'.format(
        instance.name, filename)
    full_path = os.path.join(settings.MEDIA_ROOT, banner_pic_name)

    if os.path.exists(full_path):
        os.remove(full_path)

    return banner_pic_name

# Create your models here.

GROUPS_OPTIONS=(
    ('Turismo', 'Turismo'),
    ('Deporte', 'Deporte'),
    ('Estudio', 'Estudio'),
    ('Voluntariados', 'Voluntariados'),
    ('Arte', 'Arte'),
    ('Cultura', 'Cultura'),
    ('Automotriz', 'Automotriz'),
    ('Emprendimiento', 'Emprendimiento'),
    ('Entretenimiento', 'Entretenimiento'),
)

ESTATES=(
    ('Pendiente', 'Pendiente'),
    ('Aceptada', 'Aceptada'),
    ('Rechazada', 'Rechazada'),
)


class Group(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="group")
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField(blank=True, null=True, upload_to=group_directory_path)
    description = models.TextField(max_length=400)
    category = models.CharField(blank=True, null=True, max_length=100, choices=GROUPS_OPTIONS)
    lugar = models.CharField(blank=True, null=True, max_length=100)
    urlChat = models.URLField(blank=True, null=True)
    numero_miembros = models.CharField(blank=False, null=False, max_length=200)
    created_on = models.DateTimeField(default=timezone.now)
    members = models.ManyToManyField(User, blank=True, related_name="members")
    slug = models.SlugField(unique=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Postulation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="postulant")
    group = models.ForeignKey('Group', on_delete=models.CASCADE)
    presentation = models.TextField(max_length=400)
    created_on = models.DateTimeField(default=timezone.now)
    accepted = models.CharField(blank=False, null=False, default='Pendiente',max_length=100, choices=ESTATES)

    

    






    
    

   

groups/views.py
from pickle import FALSE
from tkinter import W
from tokenize import group
from unicodedata import category
from django.shortcuts import render
from django.views import View

from django.contrib import messages

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.urls import reverse

from django.core.paginator import Paginator

from groups.models import Group, Postulation
from groups.forms import GroupModelForm, PostulationModelForm

from django.views.generic.edit import UpdateView, DeleteView
from django.urls.base import reverse_lazy

from accounts.models import Profile

from django.contrib.auth import get_user_model
User = get_user_model()

from django.db.models import Q

from django.core.mail import send_mail


import string
import random
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify

# Create your views here.

def random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

#def unique_slug_generator(instance, new_slug=None):
#     if new_slug is not None:
#         slug = new_slug
#     else:
#         slug = slugify(instance.nombre)
#         Klass = instance.__class__
#         max_length = Klass._meta.get_field('slug').max_length
#         slug = slug[:max_length]
#         qs_exists = Klass.objects.filter(slug=slug).exists()

#         if qs_exists:
#             new_slug = "{slug}-{randstr}".format(
#                 slug=slug[:max_length-5], randstr=random_string_generator(size=4))

#             return unique_slug_generator(instance, new_slug=new_slug)
#         return slug

class GroupsView(View):
    def get(self, request, *args, **kwargs):
        groups = Group.objects.filter(active=True)
        form = GroupModelForm()

        digital_products_data = None

        if groups:
            paginator = Paginator(groups, 9)
            page_number = request.GET.get('page')
            digital_products_data = paginator.get_page(page_number)
        
        context={
            'groups':digital_products_data,
            'form':form
        }
        return render(request, 'groups/groups.html', context)

    def post(self, request, *args, **kwargs):
        groups = Group.objects.filter(active=True)

        form=GroupModelForm()

        key = random_string_generator()
    
        if request.method == "POST":

            form=GroupModelForm(request.POST, request.FILES)
            if form.is_valid():
                form.user=request.user
                slug = key
                name = form.cleaned_data.get('name')
                thumbnail = form.cleaned_data.get('thumbnail')
                description = form.cleaned_data.get('description')
                category = form.cleaned_data.get('category')
                lugar = form.cleaned_data.get('lugar')
                urlChat = form.cleaned_data.get('urlChat')
                numero_miembros = form.cleaned_data.get('numero_miembros')

                p, created = Group.objects.get_or_create(user=form.user,slug=slug,name=name,thumbnail=thumbnail,description=description,category=category,lugar=lugar,urlChat=urlChat,numero_miembros=numero_miembros)
                p.save()
                return redirect("groups:group-list")

           
        digital_products_data = None

        if groups:
            paginator = Paginator(groups, 9)
            page_number = request.GET.get('page')
            digital_products_data = paginator.get_page(page_number)
        
        context={
            'groups':digital_products_data,
            'form':form
        }
        return render(request, 'groups/groups.html', context)


class GrouptDetailView(View):
    def get(self, request, slug,*args, **kwargs):
        group = get_object_or_404(Group, slug=slug)
        form = PostulationModelForm()
        context={
            'group':group,
            'form':form
        }
        return render(request, 'groups/detail.html', context)
    def post(self, request, slug, *args, **kwargs):

        if request.method == 'POST':
            form=PostulationModelForm(request.POST)
            print(form)
            if form.is_valid():
                form.user=request.user
                group = get_object_or_404(Group, slug=slug)
                presentation = form.cleaned_data.get('presentation')
                

                p, created = Postulation.objects.get_or_create(user=form.user,group=group,presentation=presentation)
                p.save()

                send_mail(
                    subject="Felicidades, te haz postulado a un grupo",
                    message="Espera la respuesta",
                    recipient_list=['henryasdrubalrodriguezmorales@gmail.com'],
                    from_email="Leviatan <henry_rodriguez23201@elpoli.edu.co>"
                )

                messages.add_message(
                self.request,
                messages.SUCCESS,
                'Te haz registrado a un grupo'
                )
                return redirect('groups:my-postulations')

        
        

class UserGroupsListView(View):
    def get(self, request, *args, **kwargs):
        groups = Group.objects.filter(user=self.request.user)
        context={
            'groups':groups
        }
        return render(request, 'groups/user_grouplist.html', context)


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    template_name="groups/edit.html"
    form_class=GroupModelForm

    def get_queryset(self):
        return Group.objects.filter(user=self.request.user)

    def get_success_url(self):
        return reverse("groups:group-list")


class MyPostulationsListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        postulations = Postulation.objects.filter(user=self.request.user)

        postulations_data = None

        if postulations:
            paginator = Paginator(postulations, 3)
            page_number = request.GET.get('page')
            postulations_data = paginator.get_page(page_number)

        context={
            'postulations':postulations_data
        }
        return render(request, 'groups/my_postulations.html', context)


class PostulationsListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        postulations = Postulation.objects.filter(group__user=self.request.user, accepted='Pendiente')

        postulations_data = None

        if postulations:
            paginator = Paginator(postulations, 6)
            page_number = request.GET.get('page')
            postulations_data = paginator.get_page(page_number)
        
        context={
            'postulations':postulations_data
        }

        return render(request, 'groups/postulations.html', context)


class GroupDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model=Group
    template_name='groups/delete.html'
    success_url = reverse_lazy("groups:group-list")
    
    def test_func(self):
        group = self.get_object()
        return self.request.user == group.user

    
class PostulationDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model=Postulation
    template_name='groups/deletePostulation.html'
    success_url = reverse_lazy("groups:my-postulations")
    
    def test_func(self):
        postulation = self.get_object()
        return self.request.user == postulation.user


class AddMember(LoginRequiredMixin, View):
    def post(self, request, postulation_pk, pk, *args, **kwargs):
        postulation = Postulation.objects.get(pk=postulation_pk)
        group = Group.objects.get(pk=pk)
        members = group.members.all()
        number_of_members = len(members)
        if number_of_members < int(group.numero_miembros):
           postulation.accepted = 'Aceptada'
           postulation.save()
           group.members.add(postulation.user)
        else:
            messages.add_message(
            self.request,
            messages.WARNING,
            'Ya no puedes ingresar más personas, si quieres cambia la cantidad de personas'
            )

        members = group.members.all()
        number_of_members = len(members)
        if number_of_members == int(group.numero_miembros):
            group.active = False
            group.save()


        return redirect("groups:postulations")


class DeclineMember(LoginRequiredMixin, View):
    def post(self, request, postulation_pk, pk, *args, **kwargs):
        postulation = Postulation.objects.get(pk=postulation_pk)
        #group = Group.objects.get(pk=pk)
        postulation.accepted = 'Rechazada'
        postulation.save()
        return redirect("groups:postulations")


class GrouptMembersView(LoginRequiredMixin, View):
    def get(self, request, slug,*args, **kwargs):
        group = get_object_or_404(Group, slug=slug)
        members = group.members.all()

        members_data = None

        if members:
            paginator = Paginator(members, 4)
            page_number = request.GET.get('page')
            members_data = paginator.get_page(page_number)
        
        context={
            'members':members_data,
            'group':group,
        }
        return render(request, 'groups/members.html', context)
        

class RemoveeMember(LoginRequiredMixin, View):
    def post(self, request, member_pk, pk, *args, **kwargs):
        member = Profile.objects.get(pk=member_pk)
        group = Group.objects.get(pk=pk)
        group.members.remove(member.user)
        return redirect("groups:members", slug=group.slug)
        

class MyGroupsListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        groups = Group.objects.filter(members=self.request.user)
        print(groups)
        context={
            'groups':groups
        }

templates/groups/my_groups.html
{% extends 'baseMarketplace.html' %}
{% load static %}

{% block title %}Grupos{% endblock title %}
{% block extra_head %}{% endblock extra_head %}

{% load humanize %}
{% load tailwind_tags %}
{% load tailwind_filters %}

{% block navbar %}
{% include 'components/navbarGroups.html' %}
{% endblock navbar %}


{% block content %}


<div >
    <div class="bg-white max-w-full  shadow px-4 py-5 sm:rounded-lg sm:p-6 mt-10">
      
            <div class="dark:bg-dark-third max-w-full px-4 py-5 border-b rounded-lg mb-2 dark:border-dark-second border-gray-200 sm:px-6">

                <h3 class="text-xl leading-6 cursor-default dark:text-dark-txt prose rounded font-bold text-gray-900">
                    Grupos registrados
                </h3>
                <p class="mt-1 text-sm cursor-default dark:text-dark-txt text-gray-500">
                    Estos son los grupos es que te aceptaron. Disfrútalos
                </p>
            </div>
            <div class="mt-12 max-w-lg mx-auto grid gap-5 lg:grid-cols-3 lg:max-w-none">
                {% for group in groups %}
                <div class="flex flex-col rounded-lg shadow-lg overflow-hidden">
                    <div class="flex-1 bg-white p-6 flex flex-col justify-between">
                        <div class="flex-1">
                            <a href="#" class="block mt-2">
                                <div class="mt-6 flex items-center">
                                    <div class="flex-shrink-0">
                                        <a href="{% url 'users:profile' username=group.user %}">
                                            <span class="sr-only">{{group.user}}</span>
                                            <img class="h-10 w-10 rounded-full" src="{{group.user.profile.picture.url}}" alt="">
                                        </a>
                                    </div>
                                    
                                    <div class="ml-3">
                                        <p class="text-sm font-medium text-gray-900">
                                            <a href="{% url 'users:profile' username=group.user %}" class="hover:underline">
                                                {{group.user}}
                                            </a>
                                        </p>
                                        <span class="text-sm text-gray-500">{{group.created_on|naturaltime}}</span>
                                    </div>
                                </div>
                                <p class="text-sm font-medium text-blue-600 py-2">
                                    <a href="{% url 'groups:group-detail' group.slug %}">
                                        {{group.name}}
                                    </a>
                                </p>
                                <p class="text-sm font-semibold text-gray-400">
                                    {{group.description}}
                                </p>
                                <p class="mt-2 max-w-4xl text-sm mx-1 dark:text-dark-txt text-gray-500 cursor-default">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 inline-block" fill="none" viewBox="0 0 24 24"
                                      stroke="currentColor">
                                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                                    </svg><a class="text-blue-500 hover:text-blue-900" href="{{group.urlChat}}" target="_blank"
                                      rel="nofollow">{{group.urlChat}}</a>
                            </a>
                            <p class="text-sm font-medium text-blue-600 pt-4">
    
                            <div class="border border-gray-200 dark:border-dark-third border-l-0 border-r-0 py-1">
                                <div class="flex space-x-2 justify-center items-center">
                        
                                    <form method="POST" action="{% url 'groups:leave-group' pk=group.pk %}" class="mt-2 px-2">
                                        {% csrf_token %}
                                        <button type="submit" class=" flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl py-2 rounded-lg cursor-pointer text-gray-500 dark:text-dark-txt">
                                            <i class='bx bx-log-out-circle'></i>
                                            <p class="text-sm font-semibold">Salir del grupo</p>
                                        </button> 
                                    </form>
                
                                  
                                </div>
                            </div>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
    </div>
</div>


{% endblock content %}


{% block javascript %}

{% endblock javascript %}

templates/groups/postulations.html
{% extends 'baseMarketplace.html' %}
{% load static %}

{% block title %}Grupos{% endblock title %}
{% block extra_head %}{% endblock extra_head %}


{% load humanize %}
{% load tailwind_tags %}
{% load tailwind_filters %}

{% block navbar %}
{% include 'components/navbarGroups.html' %}
{% endblock navbar %}


{% block content %}
<div class="relative bg-gray-50 pt-16 pb-20 px-4 sm:px-6 lg:pt-24 lg:pb-28 lg:px-8">
    <div class="absolute inset-0">
        <div class="bg-white h-1/3 sm:h-2/3"></div>
    </div>
    <div class="relative max-w-7xl mx-auto">
        <div class="text-center">
            <h2 class="text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">
                Postulaciones
            </h2>
            <p class="mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4">
                Estos son las personas que se han postulado a tu comunidad
            </p>
        </div>

        <div class="mt-12 max-w-lg mx-auto grid gap-5 lg:grid-cols-3 lg:max-w-none">
            {% for postulation in postulations %}
            <div class="flex flex-col rounded-lg shadow-lg overflow-hidden">

                <div class="flex-1 bg-white p-6 flex flex-col justify-between">
                    <div class="flex-1">
                        <a href="#" class="block mt-2">

                            <div class="mt-6 flex items-center">
                                <div class="flex-shrink-0">
                                    <a href="{% url 'users:profile' username=postulation.user %}">
                                        <span class="sr-only">{{postulation.user}}</span>
                                        <img class="h-10 w-10 rounded-full"
                                            src="{{postulation.user.profile.picture.url}}" alt="">
                                    </a>
                                </div>

                                <div class="ml-3">
                                    <p class="text-sm font-medium text-gray-900">
                                        <a href="{% url 'users:profile' username=postulation.user %}"
                                            class="hover:underline">
                                            {{postulation.user}}
                                        </a>
                                    </p>
                                    <span class="text-sm text-gray-500">{{postulation.created_on|naturaltime}}</span>
                                </div>
                            </div>
                            <p class="text-sm font-medium text-blue-600 py-2">
                                <a>
                                    {{postulation.group}}
                                </a>
                            </p>
                            <p class="text-sm font-semibold text-gray-400">
                                {{postulation.presentation}}
                            </p>
                        </a>
                        <p class="text-sm font-medium text-blue-600 pt-4">
                        <div class="border border-gray-200 dark:border-dark-third border-l-0 border-r-0 py-1">
                            <div class="flex space-x-2 justify-center items-center">

                                <form method="POST"
                                    action="{% url 'groups:add-member' postulation.pk postulation.group.pk %}"
                                    class="mt-2 px-2">
                                    {% csrf_token %}
                                    <button type="submit"
                                        class=" flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl py-2 rounded-lg cursor-pointer text-gray-500 dark:text-dark-txt">
                                        <i class='bx bxs-heart text-red-500'></i>
                                        <p class="text-sm font-semibold">Aceptar</p>
                                    </button>
                                </form>

                                <form method="POST"
                                    action="{% url 'groups:decline-member' postulation.pk postulation.group.pk %}"
                                    class="mt-2 px-2">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{request.path}}">
                                    <button type="submit"
                                        class=" flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl py-2 rounded-lg cursor-pointer text-gray-500 dark:text-dark-txt">
                                        <i class='bx bx-heart '></i>
                                        <p class="text-sm font-semibold">Rechazar</p>
                                    </button>
                                </form>
                            </div>
                        </div>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>





        {% if postulations.has_other_pages %}
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
            <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
                <div>
                    <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px" aria-label="Pagination">

                        {% if postulations.has_previous %}
                        <a href="?page={{ postulations.previous_page_number }}"
                            class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                            <span class="sr-only">Previous</span>
                            <!-- Heroicon name: solid/chevron-left -->
                            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                fill="currentColor" aria-hidden="true">
                                <path fill-rule="evenodd"
                                    d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                    clip-rule="evenodd" />
                            </svg>
                        </a>
                        {% endif %}


                        {% for i in postulations.paginator.page_range %}
                        {% if postulations.number == i %}
                        <a href="?page={{ i }}" aria-current="page"
                            class="z-10 bg-gray-50 border-gray-500 text-blue-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium">
                            {{ i }}</a>
                        {% else %}
                        <a href="?page={{ i }}" aria-current="page"
                            class="z-10 bg-indigo-50 border-indigo-500 text-blue-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium">
                            {{ i }}</a>
                        {% endif %}
                        {% endfor %}


                        {% if postulations.has_next %}
                        <a href="?page={{ postulations.next_page_number }}"
                            class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                            <span class="sr-only">Next</span>
                            <!-- Heroicon name: solid/chevron-right -->
                            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                fill="currentColor" aria-hidden="true">
                                <path fill-rule="evenodd"
                                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                    clip-rule="evenodd" />
                            </svg>
                        </a>
                        {% endif %}



                    </nav>
                </div>
            </div>
        </div>
        {% endif %}








































        <!-- {% if postulations.has_other_pages %}
        <ul class="pagination">

            {% if postulations.has_previous %}
            <li><a href="?page={{ postulations.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}



            {% for i in postulations.paginator.page_range %}
            {% if postulations.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}




            {% if postulations.has_next %}
            <li><a href="?page={{ postulations.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %} -->


    </div>
</div>

{% endblock content %}


{% block javascript %}


{% endblock javascript %}